import { Inter } from "next/font/google";
import "./globals.css";
import Body from "./body"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Social Media App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Body className={inter.className}>
        {children}
      </Body>
    </html>
  );
}
